/* Static, code-native web design. Links select documented example states; no operations run. */
(() => {
  const E=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
  const q=new URLSearchParams(location.search), id=q.get('id')||'W-03', wire=q.get('mode')==='wire';
  const meta=window.UPC_WEB.screens.find(s=>s.id===id);
  if(!meta)throw Error('Vista desconocida: '+id);
  const continuous=['W-07d','W-08b','W-08c','W-06h'].includes(id);
  const seller=meta.persona.startsWith('Camila'),who=seller?'Camila':'Sebastián',other=seller?'Sebastián':'Camila';
  const I=n=>`<svg class="icon" viewBox="0 0 24 24" aria-hidden="true"><path d="${window.UPC_ART.paths[n]||window.UPC_ART.paths.info}"/></svg>`;
  const href=(target)=>`screen.html?id=${target}${wire?'&mode=wire':''}`;
  const link=(label,target,cls='text-link')=>`<a class="${cls}" href="${href(target)}">${label}</a>`;
  const B=(label,target='',style='',icon='')=>target?`<a class="btn ${style}" href="${href(target)}">${icon?I(icon):''}${E(label)}</a>`:`<button type="button" class="btn ${style}">${icon?I(icon):''}${E(label)}</button>`;
  const badge=(label,type='',icon='')=>`<span class="badge ${type}">${icon?I(icon):''}${E(label)}</span>`;
  const A=(name='Camila',large=false)=>`<div class="avatar ${name==='Camila'?'seller':''} ${large?'large':''}" aria-label="${name}">${name==='Camila'?'CR':'ST'}</div>`;
  const art=(kind=continuous?'book':'calculator')=>`<div class="art">${window.UPC_ART.art(kind)}<div class="placeholder"><span>Imagen del aviso</span></div></div>`;
  const notice=(title,body,type='')=>`<div class="notice ${type}">${I(type==='error'?'warning':type==='warning'?'info':'shield')}<div><strong>${E(title)}</strong><p>${E(body)}</p></div></div>`;
  const F=(label,value,{help='',error=false,area=false,type='text'}={})=>`<label class="field ${error?'error':''}">${E(label)}${area?`<textarea readonly>${E(value)}</textarea>`:`<input type="${type}" readonly value="${E(value)}">`}${help?`<small>${E(help)}</small>`:''}</label>`;
  const select=(label,values,chosen=values[0])=>`<label class="field">${E(label)}<select aria-label="${E(label)}">${values.map(v=>`<option ${v===chosen?'selected':''}>${E(v)}</option>`).join('')}</select></label>`;
  const check=(label,checked=true)=>`<label class="check"><input type="checkbox" ${checked?'checked':''}>${label}</label>`;
  const campuses=['Monterrico','San Miguel','San Isidro','Villa'];
  const action=(body)=>`<div class="actions">${body}</div>`;
  const empty=(title,body,buttons='',icon='search')=>`<div class="empty">${I(icon)}<h2>${E(title)}</h2><p>${E(body)}</p>${buttons}</div>`;
  const title=(heading,desc='',eyebrow='Tu comunidad UPC',right='')=>`<div class="heading"><div><span class="eyebrow">${E(eyebrow)}</span><h1>${E(heading)}</h1><p>${E(desc)}</p></div>${right}</div>`;
  function header(auth=false){
    const active=/W-0[56]/.test(id)?'Inicio':/^W-0[78]/.test(id)?'Publicar':/^W-(09|10|11|12|13)/.test(id)?'Chats':/^W-14/.test(id)?'Perfil':id.startsWith('W-04')?'Guardados':'Inicio';
    return `<header class="topbar ${auth?'auth-top':''}"><a href="${href('W-03')}" class="brand" aria-label="UPC-X, inicio"><span class="brand-mark">x</span>UPC-X</a>${auth?'':`<nav class="topnav" aria-label="Navegación principal">${[['Inicio','W-03','home'],['Guardados','W-04','heart'],['Publicar','W-07','plus'],['Chats','W-09','chat'],['Perfil','W-14','user']].map(([name,target,ico])=>`<a href="${href(target)}" class="${active===name?'active':''} ${name==='Publicar'?'nav-publish':''}" ${active===name?'aria-current="page"':''}>${I(ico)}${name}${name==='Chats'?'<b class="count">2</b>':''}</a>`).join('')}</nav>${B('Publicar aviso','W-07','publish-top','plus')}`}<div class="account">${auth?`${I('globe')}<span>Español · Perú</span>${link('Ayuda','W-15')}`:`${A(who)}<div>${who}<small>Correo UPC verificado</small></div>`}</div></header>`;
  }
  function summary(){const draft=/^W-0[78]/.test(id);return `<aside class="panel summary stack">${art()}<div><span class="eyebrow">Aviso de referencia</span><h3 style="margin-top:10px">Calculadora científica</h3><div class="price">S/ 65.00</div></div><div class="summary-line">${I('user')}<div><small>${draft?'Autora del borrador':seller?'Comprador':'Vendedora'}</small><strong>${draft?'Camila Rojas':other+' '+(seller?'Torres':'Rojas')}</strong></div></div><div class="summary-line">${I('pin')}<div><small>Campus del aviso</small><strong>Monterrico</strong></div></div>${notice('Coordinación entre estudiantes','Acuerda un encuentro en un espacio concurrido del campus.')}</aside>`;}
  function formLayout(body){return `<div class="form-layout"><section class="panel">${body}</section>${summary()}</div>`;}
  function product(kind='calculator',state='Disponible',own=false){const name=kind==='book'?'Libro de cálculo · Vol. I':kind==='headphones'?'Audífonos inalámbricos':'Calculadora científica';return `<article class="product"><${kind==='calculator'?'a href="'+href(own?'W-06':state==='Reservado'?'W-05a':'W-05')+'"':'div'}><div style="position:relative">${art(kind)}${badge(state,state==='Reservado'?'amber':'',state==='Disponible'?'check':'lock')}</div><div class="product-content"><h3>${name}</h3><small class="muted">${kind==='headphones'?'Como nuevo · San Miguel':'Como nuevo · Monterrico'}</small><div class="row between" style="margin-top:13px"><span class="price">S/ ${kind==='book'?'35':kind==='headphones'?'80':'65'}.00</span>${I('heart')}</div><div class="meta"><span>${kind==='calculator'?'Camila R.':'Estudiante UPC'}</span><span>Correo verificado ✓</span></div></div></${kind==='calculator'?'a':'div'}></article>`;}
  function auth(){
    let body='';
    if(id==='W-01'||id==='W-01a')body=`${title('Tu próxima oportunidad está en el campus.','Crea una cuenta para comprar, vender y coordinar.','Únete a UPC-X')}<div class="stack">${F('Correo institucional',id==='W-01a'?'sebastian@gmail.com':'u202600002@upc.edu.pe',{error:id==='W-01a',help:id==='W-01a'?'Usa un correo con terminación @upc.edu.pe.':'Usaremos este correo para verificar tu acceso.'})}${F('Contraseña de tu cuenta UPC-X','ClaveDeEjemplo12',{type:'password',help:'Esta contraseña pertenece a UPC-X.'})}${check('Acepto los '+link('términos de uso y privacidad','W-17'))}${B(id==='W-01a'?'Corregir y enviar código':'Crear cuenta y enviar código','W-02','','arrow')}<p class="muted">¿Ya tienes una cuenta? ${link('Inicia sesión','W-01b')}</p></div>`;
    else if(id==='W-01b'||id==='W-01c')body=`${title('Qué bueno verte de nuevo.','Ingresa con tu correo institucional y tu contraseña de UPC-X.','Bienvenido')}<div class="stack">${id==='W-01c'?notice('No pudimos iniciar sesión','El correo o la contraseña no coinciden. Revisa tus datos.','error'):''}${F('Correo institucional','u202600002@upc.edu.pe')}${F('Contraseña','ClaveDeEjemplo12',{type:'password',error:id==='W-01c'})}${link('Olvidé mi contraseña','W-01d')}${B('Iniciar sesión','W-03','','arrow')}<p class="muted">¿Es tu primera vez? ${link('Crea tu cuenta','W-01')}</p></div>`;
    else if(['W-01d','W-01e','W-01f','W-01g','W-01h','W-01i','W-01j'].includes(id)){
      const reset=id==='W-01g'||id==='W-01j',sent=id==='W-01f',expired=id==='W-01h',done=id==='W-01i';
      body=`${title(done?'Contraseña actualizada':sent?'Revisa tu correo':expired?'El enlace venció':reset?'Elige una nueva contraseña':'Recupera tu acceso','Continúa usando tu correo institucional.','Tu cuenta')}<div class="stack">${id==='W-01e'?notice('No encontramos una cuenta activa','Revisa el correo institucional o crea una cuenta.','error'):''}${sent?notice('Enlace solicitado','Enviamos las instrucciones a u202600002@upc.edu.pe. Usa el enlace temporal para continuar.'):expired?notice('Solicita un enlace nuevo','El anterior ya no se puede utilizar.','warning'):done?notice('Ya puedes iniciar sesión','Tu contraseña de UPC-X fue actualizada.'):reset?`${F('Nueva contraseña','OtraClaveEjemplo12',{type:'password'})}${F('Repetir contraseña',id==='W-01j'?'ClaveDistinta12':'OtraClaveEjemplo12',{type:'password',error:id==='W-01j',help:id==='W-01j'?'Las contraseñas no coinciden. Corrige este campo.':'Ambas contraseñas deben coincidir antes de guardar.'})}`:F('Correo institucional','u202600002@upc.edu.pe',{error:id==='W-01e'})}${B(done?'Volver al inicio de sesión':reset?'Guardar contraseña':sent?'Volver al ingreso':expired?'Solicitar otro enlace':'Enviar enlace',done||sent?'W-01b':reset?'W-01i':'W-01f','','arrow')}${link('Volver a iniciar sesión','W-01b')}</div>`;
    }else{
      const expired=id==='W-02b',invalid=id==='W-02a',success=id==='W-02c',pending=id==='W-02d';
      body=`${title(success?'Tu correo está verificado':pending?'Verifica para continuar':expired?'Tu código venció':'Revisa tu bandeja de entrada','u202600002@upc.edu.pe','Verificación institucional')}<div class="stack">${success?notice('Todo listo para entrar','El distintivo acredita acceso al correo UPC, no la conducta de su titular.'):pending?notice('Publicar y contactar están restringidos','Completa la verificación institucional para interactuar con la comunidad.','warning'):`<label class="field">Código de seis dígitos</label><div class="otp ${invalid?'error':''}" aria-label="Código de verificación">${(expired?['—','—','—','—','—','—']:[1,2,3,4,5,invalid?0:6]).map(n=>`<span>${n}</span>`).join('')}</div>${invalid?notice('El código no coincide','Corrige los dígitos o solicita otro código.','error'):expired?notice('El código anterior expiró','Reenvía el código para completar la verificación.','warning'):'<small>Vigencia restante: 04:32 · Reenvío en 00:30</small>'}`}${B(success?'Entrar al marketplace':pending?'Completar verificación':expired?'Enviar nuevo código':'Verificar código',success?'W-03':pending||expired?'W-02':'W-02c','','arrow')}${!success?link('Cambiar correo','W-01'):''}</div>`;
    }
    return `<div class="auth-layout"><aside class="auth-story"><div><span class="eyebrow">Hecho para tu vida universitaria</span><h1>Tu campus.<br>Más posibilidades.</h1><p>Encuentra lo que necesitas. Comparte lo que ya no usas. Conecta con tu comunidad.</p></div>${art()}<div class="auth-proof">${I('shield')}Correo UPC verificado · Encuentros en campus</div></aside><section class="auth-form">${body}</section></div>`;
  }
  function filters(){return `<aside class="panel filters"><div class="row between"><h3>Filtrar avisos</h3>${I('filter')}</div>${select('Campus',['Todos los campus',...campuses],(id==='W-03a'||id==='W-03g')?'Monterrico':'Todos los campus')}<div class="filter-list"><h3>Categoría</h3>${['Calculadoras','Libros','Tecnología','Comida','Tutorías'].map((c,i)=>check(c,(id==='W-03a'||id==='W-03g')&&i===0)).join('')}</div>${select('Tipo de oferta',['Todos','Producto','Servicio','Tutoría'])}${select('Condición',['Todas','Nuevo','Como nuevo','Usado'])}<div class="field-grid">${F('Desde S/','0')}${F('Hasta S/',(id==='W-03a'||id==='W-03g')?'100':'')}</div>${B('Aplicar filtros','W-03g','','filter')}${B('Limpiar filtros','W-03','ghost')}</aside>`;}
  function catalog(){
    let content='';
    if(id==='W-03f')content=`<section class="panel">${empty('Todavía no hay avisos','Vuelve más tarde o publica la primera oferta de tu comunidad.',B('Publicar aviso','W-07','','plus'),'bag')}</section>`;
    else if(id==='W-03b')content=`<section class="panel">${empty('No encontramos coincidencias','No hay calculadoras en Monterrico por menos de S/ 20. Prueba otro precio o amplía la búsqueda.',B('Limpiar filtros','W-03','','refresh'))}</section>`;
    else if(id==='W-03d')content=`<section class="panel">${empty('No pudimos cargar los avisos','Conservamos tu consulta y filtros. Revisa tu conexión e inténtalo nuevamente.',B('Reintentar','W-03c','','refresh'),'wifi')}</section>`;
    else if(id==='W-03c')content=`<p class="muted" role="status">Cargando avisos…</p><div class="grid">${[1,2,3].map(()=>'<div class="product"><div class="skeleton"></div><div class="skeleton line"></div><div class="skeleton line"></div></div>').join('')}</div>`;
    else content=`<div class="hero"><div><span class="eyebrow">De estudiante a estudiante</span><h2>Lo que buscas,<br>más cerca de ti.</h2><p>Productos, servicios y tutorías en tu campus.</p></div>${art()}</div><div class="row between wrap" style="margin-bottom:20px"><h2 style="margin:0">Avisos recientes</h2><small>${id==='W-03g'?'1 coincidencia con estos filtros':'3 avisos de ejemplo'}</small></div><div class="row between wrap" style="margin-bottom:20px">${select('Ordenar por',['Más recientes','Precio: menor a mayor','Precio: mayor a menor'],id==='W-03e'?'Precio: menor a mayor':'Más recientes')}${B('Aplicar orden','W-03e','secondary')}</div><div class="grid">${id==='W-03e'?product('book')+product()+product('headphones'):product()+(id==='W-03g'?'':product('book')+product('headphones'))}</div>`;
    return `${title('Encuentra tu próxima oportunidad.',`Hola, Sebastián. Explora lo que comparte tu comunidad.`)}<div class="catalog ${id==='W-03a'?'show-filters':''}">${filters()}<div class="catalog-content"><div class="searchbar"><label class="searchbox">${I('search')}<input aria-label="Buscar avisos" readonly placeholder="Busca calculadoras, libros, tutorías…" value="${id==='W-03b'?'Calculadora':''}"></label>${B('Filtros','W-03a','secondary mobile-only','filter')}${B('Buscar','W-03','','search')}</div>${(id==='W-03a'||id==='W-03g')?`<p>${badge('Monterrico','rose')}${badge('Calculadoras · Hasta S/ 100','rose')}</p>`:''}${content}<div style="margin-top:24px">${notice('Tu comunidad, cerca de ti','Coordina las entregas dentro del campus. Evita compartir información sensible en público.')}</div></div></div>`;
  }
  function detail(own=false,preview=false){
    const reserved=id==='W-05a',withdrawn=id==='W-05b';
    if(withdrawn)return `<section class="panel">${empty('Este aviso ya no está disponible','Su autor retiró la publicación. Puedes conservar el historial de tus conversaciones y explorar otras ofertas.',B('Explorar avisos','W-03'),'bag')}</section>`;
    return `${title(preview?'Así se verá tu publicación':own?'Tu publicación':'Un nuevo ciclo para lo que necesitas',preview?'Revisa el contenido antes de hacerlo visible.':own?'Administra su información y disponibilidad.':'','Marketplace')}<div class="detail-layout"><div><div class="detail-art">${art()}</div><div class="thumbs">${art()}${art()}</div><div class="panel description"><h2>Acerca de este aviso</h2><p>Calculadora científica en buen estado. Ideal para los cursos de ciencias. Incluye tapa protectora y todas las teclas funcionan correctamente.</p><p>Podemos coordinar la entrega en la biblioteca de Monterrico. Puedes revisarla durante el encuentro.</p>${own||preview?'':link('Reportar publicación','W-05d')}</div></div><section class="detail-copy"><div class="row wrap">${badge(continuous?'Oferta continua':reserved?'Reservado':'Disponible',reserved?'amber':'','check')}${badge('Correo UPC verificado','','shield')}</div><h1>Calculadora científica</h1><p class="muted">Calculadoras · Publicado hoy</p><div class="price">S/ 65.00</div><div class="facts"><div><small>Condición</small><strong>Como nuevo</strong></div><div><small>Campus de entrega</small><strong>Monterrico</strong></div><div><small>Tipo de oferta</small><strong>Producto</strong></div><div><small>Disponibilidad</small><strong>Oferta única</strong></div></div><div class="seller-card">${A('Camila')}<div class="grow"><h3>Camila Rojas</h3><small>★ 4.8 · 12 entregas completadas</small></div>${link('Ver perfil','W-05c')}</div>${notice(reserved?'Ya tiene una coordinación':'Encuéntrense en el campus',reserved?'Este aviso no admite nuevas operaciones mientras está reservado.':'Acuerda un lugar concurrido y revisa el producto antes de confirmar.',reserved?'warning':'')}<div class="detail-actions">${preview?B('Publicar aviso',continuous?'W-08c':'W-08a','','check')+B('Volver a editar',continuous?'W-07d':'W-07','secondary'):own?B('Editar aviso',continuous?'W-07d':'W-07c','','edit')+(continuous?'':B('Reservar','W-06c','secondary','lock')):reserved?'<button class="btn full" disabled>No disponible para contactar</button>':B('Contactar a Camila','W-10','','chat')+B('Guardar','W-04','secondary','heart')}</div>${own&&!preview?`<div class="detail-actions">${continuous?'':B('Marcar vendido','W-06d','secondary')}${B('Pausar','W-06e','secondary')}${B('Retirar','W-06a','ghost','trash')}</div>`:''}</section></div>`;
  }
  function saved(){return `${title('Tus guardados','Vuelve a las ofertas que te interesan. Guardar no reserva el aviso.','Tu selección')}${id==='W-04a'?`<section class="panel">${empty('Tu próxima oportunidad puede estar aquí','Guarda los avisos que te interesen mientras exploras el catálogo.',B('Explorar avisos','W-03'),'heart')}</section>`:`<div class="grid">${id==='W-04b'?'':product()}${product('book','Reservado')}</div>${id==='W-04b'?`<div class="toast" style="margin-top:24px">Aviso quitado de Guardados. ${link('Deshacer','W-04')}</div>`:action(B('Quitar calculadora','W-04b','secondary','heart'))}`}`;}
  function publish(){const photo=['W-07a','W-07e'].includes(id),error=id==='W-07b',continuous=id==='W-07d';
    let body=`<div class="steps"><span class="step ${photo?'':'active'}"><b>1</b>Información</span><span class="step ${photo?'active':''}"><b>2</b>Fotografías</span><span class="step"><b>3</b>Revisión</span></div>`;
    if(photo)body+=`<h2>Muestra lo que ofreces</h2><p class="muted">Elige una portada clara. Puedes cambiarla antes de publicar.</p>${id==='W-07e'?notice('No pudimos añadir ese archivo','Usa imágenes JPG o PNG de hasta 5 MB. Las fotos anteriores se conservan.','error'):''}<div class="photo-grid" style="margin:20px 0"><div>${art()}<p style="margin-top:10px">${badge('Portada','','check')}</p></div><div class="upload">${I('upload')}<p>Añadir otra fotografía</p><small>JPG o PNG · Máximo 5 MB por archivo</small></div></div>${notice('Fotografía el artículo real','Evita incluir carnés, documentos o datos personales en las imágenes.')}${action(B('Atrás','W-07','secondary')+B('Previsualizar','W-08','','arrow'))}`;
    else body+=`<h2>${id==='W-07c'?'Actualiza tu aviso':'Cuéntanos qué ofreces'}</h2>${error?notice('Revisa los campos indicados','Completa un precio válido y selecciona el campus antes de continuar.','error'):''}<div class="field-grid" style="margin-top:22px"><div class="wide">${F('Título','Calculadora científica')}</div>${select('Tipo de oferta',['Producto','Servicio','Tutoría'],continuous?'Tutoría':'Producto')}${select('Categoría',['Calculadoras','Libros','Tecnología','Comida','Tutorías'],continuous?'Tutorías':'Calculadoras')}${F('Precio en soles',error?'-10':'65.00',{error,help:error?'Ingresa un importe de cero o mayor.':'El pago se coordina fuera de UPC-X.'})}${continuous?F('Condición','No aplica a tutorías'):select('Condición',['Nuevo','Como nuevo','Usado'],'Como nuevo')}${select('Campus de entrega',error?['Selecciona un campus',...campuses]:campuses)}${select('Disponibilidad',['Oferta única','Oferta continua'],continuous?'Oferta continua':'Oferta única')}<div class="wide">${F('Descripción','Calculadora científica en buen estado. Incluye tapa protectora. Entrega en la biblioteca de Monterrico.',{area:true})}</div></div>${continuous?`<div style="margin-top:20px">${notice('Disponibilidad recurrente','Las entregas completadas no cierran automáticamente este aviso. Puedes pausarlo o retirarlo cuando no tengas disponibilidad.')}</div>`:''}${action(B('Cancelar','W-06','secondary')+B(id==='W-07c'?'Guardar cambios':'Continuar',id==='W-07c'?'W-06':continuous?'W-08b':'W-07a','','arrow'))}`;
    return `${title(id==='W-07c'?'Editar publicación':'Comparte algo con tu comunidad.','Una buena descripción ayuda a coordinar con claridad.','Publicar aviso')}${formLayout(body)}`;
  }
  function outcome(heading,body,target='W-03',label='Volver al catálogo',icon='check'){return `<div class="panel outcome">${empty(heading,body,B(label,target,'',icon),icon)}${notice('Contexto conservado','El aviso, la conversación y sus participantes siguen vinculados al mismo recorrido.')}</div>`;}
  function dialog(heading,body,buttons,extra=''){return `<div class="modal-stage"><section class="modal" aria-label="${E(heading)}">${I('info')}<h2>${heading}</h2><p>${body}</p>${extra}${action(buttons)}</section></div>`;}
  function threads(){return `<aside class="threads"><h2>Tus conversaciones</h2><a href="${href('W-10')}" class="thread active">${A(other)}<div class="grow"><h3>${other} ${seller?'Torres':'Rojas'}</h3><p>Calculadora científica</p><p>Nos vemos en la biblioteca.</p></div><b class="count">1</b></a><a href="${href('W-09')}" class="thread">${A('Sebastián')}<div><h3>Comunidad UPC</h3><p>Otra conversación de ejemplo</p></div><b class="count">1</b></a></aside>`;}
  function chat(){if(id==='W-09a')return title('Chats','Cada conversación conserva el aviso que la originó.')+`<section class="panel">${empty('Todavía no tienes conversaciones','Encuentra una oferta y contacta a su autor para comenzar.',B('Explorar avisos','W-03'),'chat')}</section>`;
    return `${title('Conversa. Coordina. Conecta.','Tus compras y ventas, con el contexto siempre a mano.','Chats')}<div class="chat-layout ${id==='W-09'?'thread-only':''}">${threads()}<section class="conversation"><header class="conversation-header row">${A(other)}<div class="grow"><h3>${other} ${seller?'Torres':'Rojas'}</h3>${badge('Correo UPC verificado','','shield')}</div>${link('Ver aviso','W-05')}</header><div class="messages"><div class="date">HOY · 14 DE SEPTIEMBRE</div><div class="bubble ${seller?'':'mine'}">Hola, ¿la calculadora sigue disponible?<small>Sebastián · 10:42 ✓✓</small></div><div class="bubble ${seller?'mine':''}">¡Hola! Sí, está disponible. Puedo entregarla en Monterrico.<small>Camila · 10:44</small></div><div class="bubble ${seller?'':'mine'} ${id==='W-10a'?'failed':''}">Perfecto. ¿Nos encontramos a las 3 en la biblioteca?<small>Sebastián · ${id==='W-10a'?'No enviado · Reintentar':'10:45 ✓✓'}</small>${id==='W-10a'?link('Reintentar envío','W-10'):''}</div>${id==='W-10b'?`<div class="bubble ${seller?'mine':''}"><strong>Datos de cobro compartidos por Camila</strong><p style="margin:9px 0">Yape / Plin · 900 000 001<br>Titular: Camila Rojas</p><small>Número ficticio para diseño. Compartido solo en este chat.</small></div>`:`<div class="bubble ${seller?'mine':''}">Me parece bien. Confírmame la propuesta de encuentro.<small>Camila · 10:47</small></div>`}</div><div class="composer"><input readonly aria-label="Mensaje" placeholder="Escribe un mensaje…">${B('Enviar','W-10','','send')}</div></section><aside class="chat-context"><span class="eyebrow">Sobre este aviso</span>${art()}<div><h3>Calculadora científica</h3><div class="price">S/ 65.00</div><small>Monterrico · Camila Rojas</small></div>${B('Coordinar encuentro','W-11','secondary','calendar')}${seller?B('Compartir datos de cobro','W-10b','secondary','receipt'):B('Adjuntar evidencia','W-12','secondary','paperclip')}${B('Gestionar entrega',seller?'W-13k':'W-13','','check')}${id==='W-10b'?B('Editar datos de cobro','W-14e','ghost'):''}${notice('Pago externo','UPC-X no procesa pagos. Verifica el destinatario antes de transferir.')}</aside></div>`;
  }
  function agreement(){const accepted=id==='W-11b',review=id==='W-11c',warning=id==='W-11a';
    return title(accepted?'Encuentro acordado':review?'Revisa la propuesta de Sebastián':'Encuéntrense en el campus.','El acuerdo pertenece a la conversación sobre Calculadora científica.','Coordinación')+formLayout(`<div class="stack">${badge(accepted?'Aceptado por ambos':review?'Pendiente de tu respuesta':'Propuesta de encuentro',accepted?'':'amber','calendar')}<h2>${accepted?'Biblioteca · Monterrico':'Propón un lugar y un horario'}</h2>${warning?notice('El campus no coincide con el aviso','La publicación indica Monterrico. Revisa la sede antes de enviar.','warning'):''}<div class="field-grid">${select('Campus',campuses,warning?'San Miguel':'Monterrico')}${select('Punto de encuentro',['Biblioteca','Cafetería','Rotonda'])}${F('Fecha','2026-09-15',{type:'date'})}${F('Hora','15:00',{type:'time'})}</div>${F('Nota para la otra persona','Nos vemos junto al ingreso de la biblioteca.',{area:true})}${notice('Un lugar visible y concurrido','El acuerdo del encuentro no confirma la entrega ni el pago.')}${action(B('Volver al chat',seller?'W-10c':'W-10','secondary')+B(accepted?'Gestionar entrega':review?'Aceptar propuesta':warning?'Corregir campus':'Enviar propuesta',accepted?'W-13':review?'W-11b':warning?'W-11':'W-11c','','check'))}</div>`);
  }
  function payment(){const received=id==='W-12b',disputed=id==='W-12c',review=id==='W-12d',sent=id==='W-12a';
    return title(received?'Recepción declarada':disputed?'Hay una discrepancia':review?'Revisa la evidencia compartida':'Comparte una constancia, si lo necesitas.','El pago ocurre fuera de UPC-X. Adjuntar evidencia es opcional.','Evidencia de pago')+formLayout(`<div class="stack">${notice('UPC-X no valida transferencias','La captura es un respaldo aportado por un participante. Revisa tu billetera o cuenta antes de declarar la recepción.',disputed?'warning':'')}${badge(received?'Camila declaró recepción':disputed?'Camila no reconoce el pago':sent?'Compartido con Camila':review?'Compartido por Sebastián':'Sin enviar',disputed?'amber':'')}<div class="evidence"><div class="row between"><strong>Constancia compartida</strong>${I('receipt')}</div><div class="price">S/ 65.00</div><small>Canal declarado: Yape</small><small>De Sebastián Torres → Camila Rojas</small><small>Referencia ilustrativa: UPCX-001 · 15 sep 2026</small><div class="upload" style="margin-top:20px">${I('image')}<p>Captura adjunta: constancia-ejemplo.png</p><small>Representación de archivo · Datos ficticios</small></div></div>${disputed?notice('Solicitar aclaración','Camila indica que el importe aún no aparece. Conversa y comparte una corrección sin borrar el historial anterior.','warning'):''}${!received&&!review&&!sent?F('Mensaje opcional','Comparto la captura de la transferencia de S/ 65.00.') :''}${action(B('Volver al chat',seller?'W-10c':'W-10','secondary')+(review?B('No reconozco el pago','W-12c','secondary')+B('Declaro haber recibido el pago','W-12b','','check'):received||sent?B('Gestionar entrega','W-13','','check'):B(disputed?'Compartir corrección':'Compartir evidencia','W-12a','','send')))}</div>`);
  }
  function closure(){
    if(id==='W-13c')return dialog('¿Cancelar este encuentro?','Explica el motivo. Al confirmar, la coordinación se cancela y se notifica a la contraparte.',B('Volver sin cancelar','W-13','secondary')+B('Confirmar cancelación','W-13g'),F('Motivo','No podré asistir en el horario acordado.',{area:true}));
    if(id==='W-13g')return outcome('Encuentro cancelado; aviso enviado','Camila recibirá la notificación. El historial se conserva y esta coordinación no habilita reseñas.','W-10','Volver al chat','check');
    if(id==='W-13h')return dialog('Sebastián canceló el encuentro','Motivo: no podrá asistir en el horario acordado. Se conserva la conversación para aclaraciones. La cancelación ya está registrada.',B('Volver al chat','W-10c','secondary')+B('Ver cancelación','W-13i'));
    if(id==='W-13i')return outcome('Encuentro cancelado','La cancelación fue notificada a la contraparte. El chat y el historial se conservan. Esta coordinación no habilita reseñas.','W-14b','Ver historial');
    if(id==='W-13e')return title('Registrar una inasistencia','Describe lo sucedido en el encuentro acordado.','Seguimiento')+formLayout(`<div class="stack">${notice('Se registra tu declaración','No implica sanción automática ni confirmación de los hechos. La contraparte podrá conocer el reporte.','warning')}${F('Encuentro','Biblioteca · Monterrico · 15 sep 2026 · 15:00')}${F('Describe lo ocurrido','Esperé en el punto acordado y no pude encontrar a la otra persona.',{area:true})}${check('Confirmo que esta descripción refleja mi experiencia.')}${action(B('Volver','W-13','secondary')+B('Registrar inasistencia','W-13f'))}</div>`);
    if(id==='W-13f')return outcome('Inasistencia registrada','Tu declaración quedó asociada al encuentro. Puedes consultar su estado en el historial.','W-14b','Ver historial');
    if(id==='W-13d')return outcome('Tu reseña fue enviada','La valoración de Camila quedó asociada a la entrega completada por ambos. Gracias por compartir tu experiencia.','W-14b','Ver historial','star');
    const review=id==='W-13b'||id==='W-13j',pending=id==='W-13a',sellerConfirm=id==='W-13k';
    return title(review?'Tu experiencia ayuda a la comunidad.':'¿Cómo fue la entrega?','Calculadora científica · S/ 65.00 · Biblioteca, Monterrico','Cierre de la coordinación')+formLayout(`<div class="stack">${review?`${badge('Entrega confirmada por ambos','','check')}<div class="row">${A(other,true)}<div><h2>Califica a ${other}</h2><small>${seller?'Comprador':'Vendedora'} de esta coordinación</small></div></div><label class="field">Tu calificación</label><div class="stars" aria-label="5 de 5 estrellas">★★★★★</div>${F('Comentario','Puntual y trato según lo acordado.',{area:true})}${notice('Una reseña por participante','La valoración queda vinculada a esta transacción completada.')}${action(B('Volver al historial','W-14b','secondary')+B('Enviar reseña',seller?'W-14j':'W-13d','','star'))}`:`${badge(pending?'Falta la confirmación de Camila':'Encuentro aceptado',pending?'amber':'','clock')}<h2>Confirma solo si ya se realizó</h2><div class="summary-line">${I('check')}<div><strong>Sebastián Torres</strong><small>${(pending||sellerConfirm)?'Entrega confirmada':'Pendiente de confirmar'}</small></div></div><div class="summary-line">${I('clock')}<div><strong>Camila Rojas</strong><small>Pendiente de confirmar</small></div></div>${notice('Se necesitan ambas confirmaciones','La reseña se habilita cuando ambos confirman. Puedes completar una entrega sin adjuntar evidencia de pago.','warning')}${pending?'<button class="btn" disabled>Esperando confirmación de Camila</button>':B('Confirmar entrega completada',sellerConfirm?'W-13j':'W-13a','','check')}${action(B('No se presentó','W-13e','secondary')+B('Cancelar encuentro','W-13c','ghost')+B('Volver al chat',seller?'W-10c':'W-10','secondary'))}`}</div>`);
  }
  function profileMenu(){return `<aside class="panel profile-menu"><div class="row">${A(who)}<div><h3>${who} ${seller?'Rojas':'Torres'}</h3><small>Correo UPC verificado</small></div></div>${[['Mi perfil','W-14','user'],['Mis publicaciones','W-14a','bag'],['Historial','W-14b','clock'],['Mi reputación','W-14j','star'],['Datos y preferencias','W-14c','edit'],['Datos de cobro','W-14e','receipt'],['Ayuda','W-15','info'],['Cerrar sesión','W-14d','logout']].map(([t,to,ico])=>link(I(ico)+t,to,id===to?'active':'')).join('')}</aside>`;}
  function profile(){
    if(id==='W-14d')return dialog('¿Cerrar tu sesión?','Podrás volver a ingresar con tu correo y contraseña. Si tienes cambios sin guardar, vuelve y guárdalos antes de salir.',B('Volver al perfil','W-14','secondary')+B('Sí, cerrar sesión','W-01b','','logout'));
    let body='';
    if(id==='W-14c'||id==='W-14h')body=`<section class="panel stack"><h2>Datos y preferencias</h2><div class="field-grid">${F('Nombre visible',id==='W-14h'?'':'Camila Rojas',{error:id==='W-14h',help:id==='W-14h'?'Escribe tu nombre visible.':'Este nombre aparece en tus conversaciones.'})}${select('Campus frecuente',campuses)}${F('Correo institucional','u202600001@upc.edu.pe',{help:'Verificado. No se cambia desde este formulario.'})}${select('Idioma',['Español (Latinoamérica)','English (United States)'])}</div>${notice('Una sola cuenta','Tu perfil sirve para comprar y publicar. El idioma elegido debe mantenerse en toda la experiencia.')}${action(B('Cancelar','W-14','secondary')+B('Guardar cambios','W-14g','','check'))}</section>`;
    else if(id==='W-14e'||id==='W-14f')body=`<section class="panel stack"><h2>Tu información de cobro</h2><p class="muted">Se comparte únicamente cuando tú lo decides dentro de una conversación.</p>${F('Titular','Camila Rojas')}${F('Número de Yape / Plin',id==='W-14f'?'90000':'900000001',{error:id==='W-14f',help:id==='W-14f'?'Introduce los nueve dígitos del número móvil.':'Número ficticio para esta maqueta.'})}${check('Permitir compartir estos datos manualmente en mis chats.')}${notice('Tus credenciales son privadas','UPC-X nunca solicita el PIN ni las claves de tu billetera.')}${action(B('Cancelar','W-14','secondary')+B('Guardar datos','W-14g','','check'))}</section>`;
    else if(id==='W-14g')body=outcome('Cambios guardados','Tus preferencias están actualizadas. Puedes volver al perfil para continuar.','W-14','Ver perfil');
    else if(id==='W-14a'||id==='W-14i')body=`<section class="panel"><div class="row between wrap"><h2>Mis publicaciones</h2>${B('Crear aviso','W-07','','plus')}</div><div class="row wrap" style="margin:20px 0">${B('Activos','W-14a',id==='W-14a'?'':'secondary')}${B('Pausados','W-06e','secondary')}${B('Vendidos','W-14i',id==='W-14i'?'':'secondary')}</div>${['calculator','book'].map((k,i)=>`<div class="table-row"><div class="row">${art(k)}<div><h3>${i?'Libro de cálculo':'Calculadora científica'}</h3><small>Monterrico · S/ ${i?35:65}.00</small></div></div><div>${badge(id==='W-14i'?'Vendido':'Activo',id==='W-14i'?'gray':'')}</div><div>${link('Administrar','W-06')}${id==='W-14a'?`<br>${link('Pausar','W-06e')}`:''}</div></div>`).join('')}</section>`;
    else if(id==='W-14b')body=`<section class="panel"><h2>Historial de transacciones</h2><p class="muted">Tus compras y ventas conservan sus participantes y estados.</p>${[['Calculadora científica','Sebastián Torres','Completada','W-13b'],['Libro de cálculo','Estudiante UPC','Cancelada','W-13i'],['Audífonos inalámbricos','Estudiante UPC','Inasistencia declarada','W-13f']].map(([name,person,status,to])=>`<div class="table-row"><div><h3>${name}</h3><small>${person} · Septiembre 2026</small></div><div>${badge(status,status==='Completada'?'':'amber')}</div>${link('Ver detalle',to)}</div>`).join('')}</section>`;
    else if(id==='W-14j')body=`<section class="panel stack"><div class="row"><div class="price" style="font-size:48px">4.8</div><div><div class="stars">★★★★★</div><small>12 valoraciones de ejemplo</small></div></div>${[10,2,0,0,0].map((n,i)=>`<div class="rating-row"><span>${5-i} estrellas</span><div class="bar"><span style="width:${n/12*100}%"></span></div><span>${n}</span></div>`).join('')}<div class="divider"></div><h3>Lo que comparte tu comunidad</h3><p>“Puntual y trato según lo acordado.”</p><small>Valoración de una entrega completada · Datos ilustrativos</small></section>`;
    else body=`<div class="stack"><section class="panel"><div class="row">${A(who,true)}<div><h2 style="margin-bottom:8px">${who} ${seller?'Rojas':'Torres'}</h2>${badge('Correo UPC verificado','','shield')}<p style="margin:12px 0 0" class="muted">Monterrico · Comunidad UPC</p></div></div>${action(B('Editar perfil','W-14c','secondary','edit'))}</section><div class="stats"><div class="stat"><b>4.8</b><small>Reputación</small></div><div class="stat"><b>12</b><small>Entregas completadas</small></div><div class="stat"><b>2</b><small>Avisos activos</small></div></div><section class="panel stack"><h2>Tu actividad, en un solo lugar</h2><div class="row wrap">${B('Mis publicaciones','W-14a','secondary','bag')}${B('Historial','W-14b','secondary','clock')}${B('Mi reputación','W-14j','secondary','star')}${B('Datos de cobro','W-14e','secondary','receipt')}${B('Cerrar sesión','W-14d','ghost','logout')}</div>${notice('Tu rol cambia, tu cuenta no','Puedes encontrar ofertas y publicar desde el mismo perfil.')}</section></div>`;
    return title('Tu espacio en UPC-X.','Administra tus datos, tu actividad y tus preferencias.','Mi cuenta')+`<div class="profile-layout">${profileMenu()}<div>${body}</div></div>`;
  }
  function report(){if(id==='W-05e')return outcome('Recibimos tu reporte','El equipo revisará la publicación y el motivo enviado. No se retira automáticamente ni se presume una infracción.','W-03','Volver al catálogo');
    return title('Ayuda a cuidar la comunidad.','Reporta una publicación que consideres contraria a las normas.','Reporte de aviso')+formLayout(`<div class="stack"><h2>Calculadora científica · Camila Rojas</h2>${id==='W-05f'?notice('Completa tu reporte','Selecciona un motivo y describe el problema.','error'):''}${select('Motivo',['Selecciona un motivo','Producto no permitido','Información engañosa','Otro'],'Información engañosa')}${F('Describe el problema',id==='W-05f'?'':'La descripción y las fotografías parecen corresponder a productos distintos.',{area:true,error:id==='W-05f',help:id==='W-05f'?'Explica qué debe revisar el equipo.':''})}${notice('Revisión por el equipo','Tu reporte queda asociado al aviso. Su envío no equivale a una sanción.')}${action(B('Cancelar','W-05','secondary')+B('Enviar reporte','W-05e','','send'))}</div>`);
  }
  function helpLayout(body){return `<div class="form-layout"><section class="panel">${body}</section><aside class="panel stack summary"><span class="eyebrow">RichStudent · UPC-X</span><h2>Una consulta clara ayuda a orientarte.</h2><p>Incluye el contexto y la referencia de tu consulta, si la tienes.</p>${notice('Protege tu información','No incluyas contraseñas, PIN ni documentos de identidad.')}${B('Preguntas frecuentes','W-15','secondary')}</aside></div>`;}
  function help(){
    if(id==='W-16b')return outcome('Tu solicitud fue recibida','Referencia de ejemplo: UPCX-SOP-001. Conserva el código para consultar tu caso. No se ha enviado un mensaje real desde esta maqueta.','W-15','Volver a Ayuda');
    if(id==='W-16'||id==='W-16a')return title('Estamos para ayudarte.','Describe tu consulta sin incluir contraseñas ni documentos de identidad.','Contacto y soporte')+helpLayout(`<div class="stack"><h2>Enviar una consulta</h2>${id==='W-16a'?notice('Hay campos por completar','Revisa el correo, el asunto y la descripción.','error'):''}${F('Correo de respuesta','u202600002@upc.edu.pe')}${F('Asunto',id==='W-16a'?'':'Consulta sobre una coordinación',{error:id==='W-16a'})}${F('Mensaje',id==='W-16a'?'':'Necesito ayuda para consultar el estado de una cancelación.',{area:true,error:id==='W-16a'})}${check('He leído la información de privacidad para la atención de esta consulta.')}${action(B('Volver a Ayuda','W-15','secondary')+B('Enviar consulta','W-16b','','send'))}</div>`);
    if(id==='W-17')return title('Las reglas de nuestra comunidad.','Resumen de diseño para consulta durante el registro y desde el pie de página.','Términos y privacidad')+`<section class="panel stack" style="max-width:920px"><h2>Un espacio para estudiantes UPC</h2><p>Usa tu correo institucional, describe tus avisos con honestidad y respeta a las personas con las que coordinas. Reporta los contenidos que consideres indebidos.</p><h3>Pagos y encuentros</h3><p>UPC-X facilita el contacto y conserva la evidencia que decidas compartir. No procesa ni certifica transferencias. Coordina en espacios concurridos del campus y verifica el producto y el destinatario del pago.</p><h3>Privacidad y datos compartidos</h3><p>El correo verifica tu cuenta. Comparte datos de cobro o constancias solo con la contraparte. Nunca envíes claves, PIN ni documentos de identidad en el chat.</p><h3>Consulta y soporte</h3><p>Los reportes e inasistencias son declaraciones que requieren revisión. El resumen mostrado aquí acompaña el diseño y debe enlazar al acuerdo de servicio consolidado antes de publicar el producto.</p>${B('Ir al centro de ayuda','W-15','secondary')}</section>`;
    return title('¿En qué podemos ayudarte?','Respuestas claras para comprar y vender dentro de tu comunidad.','Centro de ayuda')+`<div class="form-layout"><section class="panel"><h2>Preguntas frecuentes</h2>${[['¿UPC-X procesa los pagos?','No. El pago se realiza fuera de UPC-X mediante el canal que acuerden. La evidencia compartida no acredita por sí sola una transferencia.'],['¿Dónde coordinamos la entrega?','En un punto concurrido del campus acordado: biblioteca, cafetería o rotonda. Confirmen la sede, fecha y hora en la conversación.'],['¿Qué significa correo UPC verificado?','Que la cuenta acreditó acceso a un correo @upc.edu.pe. No garantiza la conducta de su titular.'],['¿Cuándo puedo dejar una reseña?','Cuando los dos participantes confirman la entrega. Una reserva o evidencia de pago no habilita por sí sola una reseña.'],['¿Cómo reporto un problema?','Desde el detalle puedes reportar un aviso. Desde la coordinación puedes registrar una inasistencia. Para otras consultas, usa el formulario de soporte.']].map(([t,b],i)=>`<details class="faq" ${i<2?'open':''}><summary>${t}</summary><p>${b}</p></details>`).join('')}</section><aside class="panel stack summary"><h2>¿Necesitas más ayuda?</h2><p class="muted">Cuéntanos tu consulta y conserva su referencia.</p>${B('Contactar soporte','W-16','','chat')}${B('Términos y privacidad','W-17','secondary','shield')}</aside></div>`;
  }
  let content;
  if(/^W-0[12]/.test(id))content=auth();
  else if(id.startsWith('W-03'))content=catalog();
  else if(id.startsWith('W-04'))content=saved();
  else if(['W-05d','W-05e','W-05f'].includes(id))content=report();
  else if(id==='W-05c')content=title('Conoce a Camila.','Perfil público de la autora del aviso.','Comunidad UPC')+`<div class="form-layout"><section class="panel stack"><div class="row">${A('Camila',true)}<div><h2>Camila Rojas</h2>${badge('Correo UPC verificado','','shield')}<p class="muted" style="margin-top:12px">Monterrico · Vendedora en este aviso</p></div></div><div class="stats"><div class="stat"><b>4.8</b><small>Reputación</small></div><div class="stat"><b>12</b><small>Entregas completadas</small></div><div class="stat"><b>2</b><small>Avisos activos</small></div></div><h3>Reseñas de la comunidad</h3><p>“Puntual y producto según lo descrito.”</p><small>Ejemplo de valoración vinculada a una entrega.</small>${B('Volver al aviso','W-05','secondary')}</section>${summary()}</div>`;
  else if(id.startsWith('W-05'))content=detail();
  else if(id==='W-06'||id==='W-06h')content=detail(true);
  else if(id==='W-06a')content=dialog('¿Retirar la publicación?','Calculadora científica dejará de aparecer en el catálogo. El historial de las conversaciones se conserva.',B('Mantener publicada','W-06','secondary')+B('Sí, retirar','W-06b','','trash'));
  else if(id==='W-06b')content=outcome('Publicación retirada','La calculadora dejó de aparecer en el catálogo. Tus conversaciones anteriores se conservan.','W-14a','Ir a mis publicaciones');
  else if(id==='W-06c')content=title('Reserva para una conversación.','La reserva debe pertenecer al mismo aviso y no puede duplicarse.','Administrar disponibilidad')+formLayout(`<div class="stack"><h2>¿Con quién coordinarás?</h2><div class="panel row">${A('Sebastián')}<div><h3>Sebastián Torres</h3><small>Conversación sobre Calculadora científica</small></div>${I('check')}</div>${notice('Una reserva activa por aviso','Mientras esté reservado, no se podrán iniciar nuevas operaciones.','warning')}${action(B('Cancelar','W-06','secondary')+B('Reservar para Sebastián','W-06g','','lock'))}</div>`);
  else if(id==='W-06d')content=dialog('¿Marcar este aviso como vendido?','La oferta única dejará de estar disponible. Esta acción no confirma por la contraparte ni habilita reseñas.',B('Volver','W-06','secondary')+B('Confirmar vendido','W-14i','','check'));
  else if(id==='W-06e')content=outcome('Tu publicación está pausada','Ya no aparece entre las ofertas disponibles. Puedes reactivarla conservando su información.','W-06f','Reactivar publicación','refresh');
  else if(id==='W-06f')content=outcome('Publicación reactivada','El mismo aviso vuelve a estar disponible con sus datos y fotografías.','W-06','Ver mi publicación');
  else if(id==='W-06g')content=outcome('Reserva confirmada para Sebastián','La calculadora queda vinculada a esta coordinación. No admitirá otra reserva simultánea.','W-10c','Volver a la conversación','lock');
  else if(id.startsWith('W-07'))content=publish();
  else if(id==='W-08'||id==='W-08b')content=detail(true,true);
  else if(id==='W-08c')content=outcome('Tu oferta continua ya está publicada','La disponibilidad recurrente se mantiene hasta que pauses o retires la oferta.','W-06h','Ver mi publicación','bag');
  else if(id==='W-08a')content=outcome('Tu aviso ya está en UPC-X.','Tu comunidad puede descubrir la calculadora y ponerse en contacto contigo.','W-06','Ver mi publicación','bag');
  else if(/^W-(09|10)/.test(id))content=chat();
  else if(id.startsWith('W-11'))content=agreement();
  else if(id.startsWith('W-12'))content=payment();
  else if(id.startsWith('W-13'))content=closure();
  else if(id.startsWith('W-14'))content=profile();
  else content=help();
  if(continuous)content=content.replaceAll('Calculadora científica','Tutoría de cálculo').replaceAll('Calculadoras · Publicado hoy','Tutorías · Publicado hoy').replaceAll('S/ 65.00','S/ 30.00').replaceAll('value="65.00"','value="30.00"').replaceAll('Oferta única','Oferta continua').replaceAll('<strong>Como nuevo</strong>','<strong>No aplica a tutorías</strong>').replaceAll('<strong>Producto</strong>','<strong>Tutoría</strong>').replaceAll('Calculadora científica en buen estado. Ideal para los cursos de ciencias. Incluye tapa protectora y todas las teclas funcionan correctamente.','Tutorías de cálculo para repasar ejercicios y resolver dudas. Sesiones de una hora, previa coordinación.').replaceAll('Tutoría de cálculo en buen estado. Ideal para los cursos de ciencias. Incluye tapa protectora y todas las teclas funcionan correctamente.','Tutorías de cálculo para repasar ejercicios y resolver dudas. Sesiones de una hora, previa coordinación.').replaceAll('Tutoría de cálculo en buen estado. Incluye tapa protectora. Entrega en la biblioteca de Monterrico.','Tutoría de cálculo de una hora. Repaso de ejercicios en la biblioteca de Monterrico.').replaceAll('Puedes revisarla durante el encuentro.','Coordinamos el tema antes de cada sesión.');
  const isAuth=/^W-0[12]/.test(id);
  document.body.classList.toggle('wire',wire);document.body.classList.toggle('export',q.has('export'));
  document.title=`${id} · ${meta.title} · UPC-X web`;
  document.querySelector('#app').innerHTML=header(isAuth)+`<main class="page ${id==='W-03a'?'show-filters':''}" id="main">${isAuth?'':`<nav class="breadcrumbs" aria-label="Ruta de navegación">${link('Marketplace','W-03')}<span>/</span><span>${E(meta.title)}</span></nav>`}${content}</main><footer class="site-footer"><span>© 2026 RichStudent · UPC-X</span><nav>${link('Ayuda','W-15')}${link('Términos y privacidad','W-17')}${link('Contactar soporte','W-16')}</nav></footer>`;
  document.querySelector('#inspector').innerHTML=`<div><strong>${id} · ${E(meta.title)}</strong><br>${meta.persona} · ${wire?'Wireframe':'Mock-up'} · Datos ilustrativos. Vista estática: los enlaces abren otros estados de ejemplo.</div><nav><a href="index.html">Galería</a> · <a href="screen.html?id=${id}${wire?'':'&mode=wire'}">${wire?'Ver mock-up':'Ver wireframe'}</a></nav>`;
  window.UPC_WEB_READY=true;
})();
